name: release PDF

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: chmod for github actions docker
      run: chmod -R 777 .

    - name: Generate PDF
      run: docker run --rm -v .:/honkit nishidemasami/markdown-docs:v1.2.0 npx honkit pdf ./ ./output.pdf

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: documents
        path: ./output.pdf

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: PDF Release
        tag_name: pdf_relrase
        generate_release_notes: true
        files: ./output.pdf

    - name: Generate pages
      run: docker run --rm -v .:/honkit nishidemasami/markdown-docs:v1.2.0 npx honkit build

    - name: Push to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: _book/